# postgres deployment object

#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deployment
spec:
  selector:
    matchLabels:
      app: healthapp
  replicas: 2
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
        - name: healthapp
          image: punugupatimahesh/healthapp:1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: healthapp-config
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgredb
#      volumes:
#        - name: postgredb
#          persistentVolumeClaim:
#            claimName: postgres-pv-claim