# postgres config map object

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: hospital
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
